fixtures:
  repositories:
    stdlib: 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.3.2"
    concat: 
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref:  "1.1.2"
  symlinks:
    selenium: "#{source_dir}"